import { Poppins } from 'next/font/google'
import { cn } from '@/lib/utils'
import './globals.css'

export const metadata = {
  title: "Dev Bathani",
  description: "Generated by Dev Bathani",
};

const fontHeading = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
  weight: '700', // Specify the weight for the heading font
})

const fontBody = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
  weight: '400', // Specify the weight for the body font
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          'antialiased',
          fontHeading.variable,
          fontBody.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
