/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lvSwODz48y1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function Portfolio() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-8 md:py-12 lg:py-16">
        <div className="container mx-auto">
          <div className="grid gap-6 md:grid-cols-2 md:gap-12 items-center">
            <div>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold">
                Dev Bathani
              </h1>
              <p className="text-xl md:text-2xl mt-2 text-primary-foreground/80">
                Flutter Engineer
              </p>
              <p className="mt-4 max-w-[600px] text-primary-foreground/90">
                Hello! I'm a seasoned Flutter developer with 4 years of
                experience, passionate about transforming ideas into reality
                through mobile applications. Over my career, I've developed over
                15 full-fledged applications, demonstrating my ability to bring
                creative concepts to life. Currently, I'm delving into Android
                Native development, using my journey to explore new technologies
                and deepen my expertise.
              </p>
            </div>
            <div className="flex justify-end">
              <img
                src="/myImage.png"
                width="300"
                height="300"
                alt="Dev Bathani"
                className="rounded-full w-48 h-48 md:w-64 md:h-64"
                style={{ aspectRatio: "300/300", objectFit: "cover" }}
              />
            </div>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">
                Featured Projects
              </h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground">
                Check out some of my recent projects that showcase my skills and
                expertise.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-8">
              <Card>
                <CardContent>
                  <img
                    src="/social_media_app_image.png"
                    width="300"
                    height="200"
                    alt="Social Media App"
                    className="rounded-t-lg w-full object-cover"
                    style={{ aspectRatio: "300/200", objectFit: "contain" }}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold">Social Media App</h3>
                    <p className="text-muted-foreground mt-2">
                      A Social Media App which is built in Flutter and NodeJs
                      with exciting features in it
                    </p>
                    <div className="mt-4">
                      <a
                        href="/social_media_app.apk"
                        download="social_media_app.apk"
                        className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      >
                        View Project
                      </a>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="mt-4">
                  <img
                    src="/planetroid_game_image.png"
                    width="300"
                    height="200"
                    alt="Planetroid Game"
                    className="rounded-t-lg w-full object-cover"
                    style={{ aspectRatio: "300/200", objectFit: "contain" }}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold">Planetroid Game</h3>
                    <p className="text-muted-foreground mt-2">
                      A web app game built in Flutter and Flame using Tiled.
                    </p>
                    <div className="mt-5">
                      <Link
                        href="https://github.com/devbathani/Planetroid-Game"
                        className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        View Project
                      </Link>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent>
                  <img
                    src="/package_image.png"
                    width="300"
                    height="200"
                    alt="Flutter Weekday Selector Package"
                    className="rounded-t-lg w-full object-cover"
                    style={{ aspectRatio: "300/200", objectFit: "contain" }}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold">
                      Flutter Weekday Selector Package
                    </h3>
                    <p className="text-muted-foreground mt-2">
                      A flutter package which provides a widget which help user
                      select specific day in a week
                    </p>
                    <div className="mt-4">
                      <Link
                        href="https://github.com/devbathani/flutter_weekday_selector"
                        className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        View Project
                      </Link>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16 lg:py-20">
          <div className="container mx-auto">
            <div className="grid gap-8 md:grid-cols-2 items-center">
              <div>
                <img
                  src="/myImage.png"
                  width="500"
                  height="400"
                  alt="About"
                  className="rounded-lg w-full object-cover"
                  style={{ aspectRatio: "500/400", objectFit: "contain" }}
                />
              </div>
              <div>
                <h2 className="text-3xl md:text-4xl font-bold">About Me</h2>
                <p className="mt-4 text-muted-foreground">
                  Hello! I'm Dev Bathani, a dedicated Flutter developer with 4
                  years of experience in creating dynamic and user-friendly
                  mobile applications. My passion for technology and innovation
                  has driven me to develop over 15 full-fledged apps, each
                  crafted with a keen eye for detail and a commitment to
                  excellence.
                </p>
                <p className="mt-4 text-muted-foreground">
                  Currently, I'm expanding my expertise by diving into Android
                  Native development, exploring new technologies, and mastering
                  the intricacies of native app creation. I believe in the power
                  of continuous learning and enjoy the challenge of bringing
                  creative ideas to life through code.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">Contact Me</h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground">
                Feel free to reach out to me if you have any questions or would
                like to discuss a potential project.
              </p>
            </div>
            <form
              className="max-w-md mx-auto mt-8 space-y-4"
              action="https://formsubmit.co/b02716cb3855e6481feb20588492d3ac"
              method="POST"
            >
              <Input
                type="name"
                placeholder="Name"
                className="w-full px-4 py-3 rounded-md bg-background text-foreground focus:ring-1 focus:ring-primary focus:border-primary"
              />
              <Input
                type="email"
                placeholder="Email"
                className="w-full px-4 py-3 rounded-md bg-background text-foreground focus:ring-1 focus:ring-primary focus:border-primary"
              />
              <Textarea
                id="message"
                placeholder="Message"
                className="w-full px-4 py-3 rounded-md bg-background text-foreground focus:ring-1 focus:ring-primary focus:border-primary"
              />
              <Button
                type="submit"
                className="w-full px-4 py-3 rounded-md bg-primary text-primary-foreground font-medium transition-colors hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-1"
              >
                Send Message
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-6 w-full shrink-0">
        <div className="container mx-auto flex flex-col md:flex-row items-center justify-between">
          <p className="text-sm">
            &copy; 2024 Dev Bathani. All rights reserved.
          </p>
          <nav className="flex items-center space-x-4 mt-4 md:mt-0">
            <Link
              href="https://www.linkedin.com/in/devbathani/"
              className="text-sm hover:underline underline-offset-4"
              prefetch={false}
              target="_blank"
              rel="noopener noreferrer"
            >
              LinkedIn
            </Link>
            <Link
              href="https://github.com/devbathani"
              className="text-sm hover:underline underline-offset-4"
              prefetch={false}
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub
            </Link>
            <Link
              href="https://x.com/BathaniDev"
              className="text-sm hover:underline underline-offset-4"
              prefetch={false}
              target="_blank"
              rel="noopener noreferrer"
            >
              Twitter
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
